# Generated by Django 4.2.2 on 2023-09-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationsXlsxConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('ru', models.TextField()),
                ('uz', models.TextField()),
                ('en', models.TextField()),
                ('origin_service', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'translations_collector"."translations_xlsx_converter',
            },
        ),
    ]
