# Generated by Django 4.2.2 on 2023-09-13 11:16

from django.db import migrations


def generate(apps, schema_editor):
    TranslationsXlsxConverter = apps.get_model("translations_xlsx_converter", "TranslationsXlsxConverter")

    TranslationsXlsxConverter.objects.get_or_create(
        pk=-1,
        defaults={
            "key": "Ключ(!!НЕ ИЗМЕНЯТЬ!!!)",
            "ru": "ru",
            "uz": "uz",
            "en": "en",
            "origin_service": "",
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('translations_xlsx_converter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate),
    ]
